---
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.4
  amd64: ghcr.io/hassio-addons/base:15.0.4
  armv7: ghcr.io/hassio-addons/base:15.0.4
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
