---
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.2
  amd64: ghcr.io/hassio-addons/base:15.0.2
  armv7: ghcr.io/hassio-addons/base:15.0.2
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
