#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: AdGuard Home
# Runs the AdGuard Homee server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a options

options+=(--port 3001)

# RUN AdGuard Home server
cd /opt/AdGuardHome || exit
exec ./AdGuardHome "${options[@]}"
