#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: AdGuard Home
# Runs the AdGuard Homee server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a options

options+=(--port 37043)
options+=(--host 127.0.0.1)

# RUN AdGuard Home server
cd /data || exit
exec ./AdGuardHome "${options[@]}"
